# Generated by Django 3.1.7 on 2021-05-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plasmadonor', '0002_auto_20210517_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='d_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plasmadonor.customer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('currrent_situation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plasmadonor.customer')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plasmadonor.donor')),
            ],
        ),
    ]
