# Generated by Django 3.1.7 on 2021-05-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmadonor', '0003_auto_20210518_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='order_status',
            field=models.CharField(choices=[('Request Received', 'Request Received'), ('Request Pending', 'Request Processing'), ('Request Accepted', 'Request Accepted'), ('Request Cancelled', 'Request Cancelled')], default='Request Pending', max_length=50),
        ),
    ]
