# Generated by Django 3.1.7 on 2021-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmadonor', '0004_requests_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='when_Recovered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='requests',
            name='currrent_situation',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='requests',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
