# Generated by Django 3.1.7 on 2021-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmadonor', '0005_auto_20210519_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='when_Recovered',
            field=models.DateTimeField(),
        ),
    ]
